name: Release Build
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+*
  workflow_dispatch:
env:
  SUBWASM_VERSION: 0.16.1
jobs:
  checks-and-tests:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install & display rust toolchain
      run: rustup show

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Check all features compilation
      run: cargo check --verbose --all-features

    - name: Run all tests
      run: cargo test --all-features

  native-linux:
    needs: checks-and-tests
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install & display rust toolchain
      run: rustup show

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Build optimized binary
      run: CARGO_PROFILE_RELEASE_LTO=true RUSTFLAGS="-C codegen-units=1" cargo build --release --verbose

    - uses: actions/upload-artifact@v3
      with:
        name: llama-web3-ubuntu-latest-x86_64
        path: target/release/llama-web3





    


    
